class_weights:
  ggh: 212.5
  qqh: 2345.8
  ztt: 1.6
  zll: 20.0
  w: 7.9
  tt: 52.9
  ss: 6.8
  misc: 51.4
classes:
- ggh
- qqh
- ztt
- zll
- w
- tt
- ss
- misc
datasets:
- ml/2016_mt/fold0_training_dataset.root
- ml/2016_mt/fold1_training_dataset.root
event_weights: training_weight
global_weight_scale: 1.0
model:
  batch_size: 100
  early_stopping: 50
  epochs: 100000
  name: smhtt_dropout_tanh
  save_best_only: true
output_path: ml/2016_mt
preprocessing: standard_scaler
seed: 1234
train_test_split: 0.75
variables:
- m_sv
- m_vis
- ptvis
- pt_1
- pt_2
- jpt_2
- jm_1
- jm_2
- bpt_1
- bpt_2
- bcsv_1
- bcsv_2
- njets
- nbtag
- mt_1
- mt_2
- pt_tt
- mjj
- dijetpt
- met
