class_weights:
  ggh: 159.9594151266507
  misc: 80.72465015562217
  qqh: 1579.8438704773116
  ss: 9.443663158233608
  tt: 197.76577135159224
  w: 13.423610185188634
  zll: 20.11131419671037
  ztt: 1.3412715355284768
classes:
- ss
- zll
- tt
- misc
- qqh
- w
- ztt
- ggh
datasets:
- ml/2016_mt/fold0_training_dataset.root
- ml/2016_mt/fold1_training_dataset.root
event_weights: training_weight
global_weight_scale: 1.0
model:
  batch_size: 100
  early_stopping: 50
  epochs: 100000
  name: smhtt_dropout_tanh
  save_best_only: true
output_path: ml/2016_mt
preprocessing: standard_scaler
seed: 1234
train_test_split: 0.75
variables:
- m_sv
- m_vis
- ptvis
- pt_1
- pt_2
- jpt_2
- jm_1
- jm_2
- bpt_1
- bpt_2
- bcsv_1
- bcsv_2
- njets
- nbtag
- mt_1
- mt_2
- pt_tt
- mjj
- dijetpt
- met
