class_weights:
  ggh: 221.4
  qqh: 1993.7
  ztt: 2.2
  zll: 7.0
  w: 6.1
  tt: 15.2
  ss: 6.3
  misc: 52.5

classes:
- ss
- zll
- tt
- misc
- qqh
- w
- ztt
- ggh
datasets:
- ml/2016_et/fold0_training_dataset.root
- ml/2016_et/fold1_training_dataset.root
event_weights: training_weight
global_weight_scale: 1.0
model:
  batch_size: 100
  early_stopping: 50
  epochs: 100000
  name: smhtt_dropout_tanh
  save_best_only: true
output_path: ml/2016_et
preprocessing: standard_scaler
seed: 1234
train_test_split: 0.75
variables:
- m_sv
- m_vis
- ptvis
- pt_1
- pt_2
- jpt_1
- jcsv_2
- jm_1
- bpt_1
- bpt_2
- bcsv_1
- bcsv_2
- njets
- nbtag
- mt_1
- mt_2
- pt_tt
- mjj
- dijetpt
- met
